# Generated by Django 2.2.4 on 2022-10-11 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bhp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='num_passengers',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1902), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
