# Generated by Django 2.2.4 on 2022-10-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_auto_20221011_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powersource',
            old_name='souce',
            new_name='source',
        ),
    ]
