# Generated by Django 2.2.4 on 2022-10-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_auto_20221012_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='car_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='car_app.Car'),
        ),
    ]
