from django.urls import path
from . import views

urlpatterns = [
    path('log/reg', views.index),
    path('my_request', views.my_request),
    path('check_register', views.check_register),
    path('check_login', views.check_login),
    path('logout', views.logout),
    path('dashboard', views.dashboard),
    path('', views.logout),
    path('my_cars', views.my_cars),
    path('add_car', views.add_car),
    path('car/new', views.create_car),
    path('car/<int:id>/view', views.view_car),
    path('car/<int:id>/request', views.request),
    path('comment/<int:id>', views.comment),
    path('car/<int:id>/posts', views.car_posts),
    path('comm/<int:id>/posts', views.car_posts),
    path('post/<int:id>', views.post),
    path('car/<int:id>/edit', views.edit_car),
    path('car/<int:id>/update', views.update_car),
    path('goback/<int:id>', views.goback),
    path('deleteCar/<int:id>', views.delete_car),
    path('car/search', views.search_car),
    path('addColor', views.addColor),
    path('addCity', views.addCity),
    path('addManufacturer', views.addManufacturer),
    path('addModel', views.addModel),
    path('addPs', views.addPowerSource),
    path('deleteCity/<int:id>', views.deleteCity),
    path('deleteColor/<int:id>', views.deleteColor),
    path('deleteManufacturer/<int:id>', views.deleteManufacturer),
    path('deleteModel/<int:id>', views.deleteModel),
    path('deletePs/<int:id>', views.deletePowerSource),
    path('deleteRequest/<int:id>', views.deleteRequest),
    path('deleteComment/<int:id>', views.deleteComment),
    path('123', views.admin),
    path('about_us', views.about_us),
    path('contact_us', views.contact_us),
]